version: '3.4'

services:
  app1:
    build: ./webapp 
    container_name: app1
    command: 9001 "Server 1"
    ports: 
      - "9001:9001"

  app2:
    build: ./webapp
    container_name: app2
    command: 9002 "Server 2"
    ports: 
      - "9002:9002"

  app3:
    build: ./webapp
    container_name: app3
    command: 9003 "Server 3"
    ports: 
      - "9003:9003"

  haproxy:
    build: ./haproxy
    container_name: haproxy
    ports:
      - "8000:80"
      - "8003:83"

  